const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPE_ERROR: 2,
    DATABASE_ERROR: 3,
    INVALID_CREDENTIALS: 4,
    USER_NOT_FOUND: 5,
    PASSWORD_MISMATCH: 6,
    PRODUCT_ERROR: 7,
}

export default EErrors